version: '3.8'

services:
  lv-weather:
    build: .
    volumes:
      - ./output:/app/output:z
    networks:
      - weather-net
    # Add the restart policy here
    restart: unless-stopped # Or 'always', depending on your needs

networks:
  weather-net:
    driver: bridge
