version: '3.8'

services:
  lv-weather:
    build: .
    volumes:
      - ./output:/app/output:z
    networks:
      - weather-net
    restart: unless-stopped

networks:
  weather-net:
    driver: bridge
